version: '3.8'

volumes:
  pg_volume:

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres7"]
       interval: 5s
       timeout: 5s
       retries: 5

  backend:
    build: ../pronin_test_task
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
