# Generated by Django 4.2.3 on 2023-07-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Имя покупателя"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название камня"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientGem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        verbose_name="Количество камней в сделке"
                    ),
                ),
                ("costs", models.PositiveBigIntegerField(verbose_name="Цена сделки")),
                (
                    "deal_date",
                    models.DateTimeField(db_index=True, verbose_name="Дата сделки"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_gem",
                        to="data_handler.client",
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "gem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gem_client",
                        to="data_handler.gem",
                        verbose_name="Камень",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="gems",
            field=models.ManyToManyField(
                related_name="clients",
                through="data_handler.ClientGem",
                to="data_handler.gem",
                verbose_name="Камни",
            ),
        ),
    ]
